name: Bump version
on:
    push:
        branches:
            - main
        paths-ignore:
            - '.github/**' # Prevent workflow loops when committing workflow files

jobs:
    bump-version:
        runs-on: ubuntu-22.04
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: '0'

            - name: Bump version and push tag
              id: tag_version
              uses: anothrNick/github-tag-action@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.TAG_TOKEN }}
                  WITH_V: true
                  PRERELEASE: true

            - name: Output new tag
              run: echo "Created new tag ${{ steps.tag_version.outputs.new_tag }}"

            - name: Automated Version Bump
              uses: 'phips28/gh-action-bump-version@master'
              with:
                  tag-prefix: ''
              env:
                  GITHUB_TOKEN: ${{ secrets.TAG_TOKEN }}
