name: Test, Build & Release
run-name: Test, Build & Release
on:
    push:
        branches:
            - main
        tags:
            - v*
    pull_request:
        branches:
            - main

jobs:
    test:
        name: Run Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test

    build-and-release:
        name: Build & Release
        needs: test
        runs-on: windows-latest
        if: success()
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - name: Build application
              run: npm run make
            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      out/make/squirrel.windows/x64/*.exe
                      out/make/zip/win32/x64/*.zip
                  generate_release_notes: true
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
