name: Test, Build & Release
run-name: Test, Build & Release
on:
    push:
        branches:
            - main
        tags:
            - v*
    pull_request:
        branches:
            - main

jobs:
    test:
        name: Run Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test

    build-and-release:
        name: Build & Release
        needs: test
        runs-on: windows-latest
        # Only run this job for tag pushes (not branch pushes)
        if: startsWith(github.ref, 'refs/tags/')
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci

            # Debug information
            - name: Display tag information
              run: echo "Building release for tag ${{ github.ref_name }}"

            - name: Build application
              run: npm run make

            # Check what files were actually created
            - name: List build artifacts
              shell: cmd
              run: |
                  echo "Checking build outputs..."
                  dir out\make /s

            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  # Adjust these paths if needed based on the dir output
                  files: |
                      out/make/squirrel.windows/x64/*.exe
                      out/make/zip/win32/x64/*.zip
                  generate_release_notes: true
                  draft: false
                  prerelease: ${{ contains(github.ref, '-pre') }}
                  # Use the tag name directly since we only run on tag events
                  tag_name: ${{ github.ref_name }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
